# -*- coding: utf-8 -*-
"""perception_integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121nhKtKe1cm7hANl5tGYnWm8S65PC1sp
"""

import cv2
import numpy as np
import onnxruntime as ort
from controller import Robot, Camera

# Load ONNX model
session = ort.InferenceSession("best.onnx")

# Initialize robot + camera
robot = Robot()
timestep = int(robot.getBasicTimeStep())
camera = robot.getDevice("camera")
camera.enable(timestep)

while robot.step(timestep) != -1:
    img = camera.getImage()
    # convert to numpy etc.
    # run model
    # draw boxes
    # output result